/**
 * Generate tests/screenshot-manifest.json — the canonical list of expected
 * screenshots AND the pointer to their bytes. Each entry is
 * {name, engine, sha256, bytes, width, height}: the engine comes from the
 * baseline cache tree (baseline-screenshots/<engine>/<name>.png), the sha256
 * resolves the PNG in the private R2 bucket (`sha256/<hex>.png`). The manifest
 * is the SOURCE OF TRUTH — the local tree is a cache materialized from it by
 * r2-sync (`npm run screenshots:fetch`).
 *
 * promote.ts is the single writer: it regenerates this file after applying and
 * uploading a CI run's render. Regeneration therefore needs the local tree
 * present; --check deliberately does NOT (it must stay credential- and
 * network-free so it can gate every CI caller, secretless ones included).
 *
 * CLI (from tests/):  tsx tools/screenshots/gen-manifest.ts [--check [--remote]]
 *   --check   exit 1 unless the committed manifest is well-formed (v2 schema,
 *             sorted+unique entries, valid hashes) and no baseline PNG has been
 *             re-committed to git (resurrection guard).
 *   --remote  with --check: also HEAD every hash in R2 (needs credentials;
 *             manual use only, not wired into CI).
 */
import * as fs from 'fs';
import * as path from 'path';
import { execFileSync } from 'child_process';
import { PNG } from 'pngjs';
import {
    BASELINE_ROOT,
    ENGINES,
    IGNORE_SCREENSHOTS,
    MANIFEST_PATH,
    MANIFEST_VERSION,
    R2_DEFAULT_BUCKET,
    R2_KEY_PREFIX,
    isIgnored,
    listEngineKeys,
    splitKey,
    type Manifest,
    type ManifestEntry,
} from './config';
import { hashFile, missingEnv, storeFromEnv } from './r2-store';

/** Locale-independent (code-unit) ordering — the writer runs on dev machines,
 *  the --check gate on CI, and localeCompare's result depends on the host locale. */
function compareEntries(a: { engine: string; name: string }, b: { engine: string; name: string }): number {
    if (a.engine !== b.engine) return a.engine < b.engine ? -1 : 1;
    return a.name < b.name ? -1 : a.name > b.name ? 1 : 0;
}

const NOTE =
    'Baselines live in R2, content-addressed by sha256 — the local baseline-screenshots/ tree is a cache ' +
    '(`npm run screenshots:fetch`). Regenerated by `npm run screenshots:promote`; never edit hashes by hand. ' +
    'The name list is authoritative for removed-screenshot detection.';

/** Render the manifest JSON for the current baseline cache tree (tree must be present). */
export function manifestJson(root: string): string {
    const base = path.join(root, BASELINE_ROOT);
    const screenshots: ManifestEntry[] = listEngineKeys(base)
        .filter((key) => !isIgnored(key))
        .map((key) => {
            const { engine, name } = splitKey(key);
            const file = path.join(base, key);
            const png = PNG.sync.read(fs.readFileSync(file));
            return {
                name,
                engine,
                sha256: hashFile(file),
                bytes: fs.statSync(file).size,
                width: png.width,
                height: png.height,
            };
        })
        .sort(compareEntries);

    const manifest: Manifest & { _note: string } = {
        _note: NOTE,
        version: MANIFEST_VERSION,
        storage: { bucket: R2_DEFAULT_BUCKET, keyPrefix: R2_KEY_PREFIX },
        screenshots,
    };
    return JSON.stringify(manifest, null, 2) + '\n';
}

/** Regenerate the manifest on disk (used by the CLI and by promote.ts after apply). */
export function writeManifest(root: string): void {
    fs.writeFileSync(path.join(root, MANIFEST_PATH), manifestJson(root));
}

/** Schema + hygiene problems with the committed manifest (empty = healthy). Credential-free. */
export function checkManifest(root: string): string[] {
    const problems: string[] = [];
    const p = path.join(root, MANIFEST_PATH);
    if (!fs.existsSync(p)) return [`${MANIFEST_PATH} is missing`];
    let manifest: Manifest;
    try {
        manifest = JSON.parse(fs.readFileSync(p, 'utf8')) as Manifest;
    } catch (e) {
        return [`${MANIFEST_PATH} is not valid JSON: ${(e as Error).message}`];
    }
    if (manifest.version !== MANIFEST_VERSION) problems.push(`version is ${manifest.version}, expected ${MANIFEST_VERSION}`);
    if (!manifest.storage?.bucket || !manifest.storage?.keyPrefix) problems.push('storage.bucket/keyPrefix missing');
    if (!Array.isArray(manifest.screenshots) || manifest.screenshots.length === 0) {
        problems.push('screenshots list is missing or empty');
        return problems;
    }

    const engines = new Set<string>(ENGINES);
    let prev: ManifestEntry | null = null;
    const seen = new Set<string>();
    for (const e of manifest.screenshots) {
        const id = `${e.engine}/${e.name}`;
        if (!e.name?.toLowerCase().endsWith('.png')) problems.push(`${id}: name is not a .png`);
        if (!engines.has(e.engine)) problems.push(`${id}: unknown engine`);
        if (!/^[0-9a-f]{64}$/.test(e.sha256 ?? '')) problems.push(`${id}: sha256 is not 64 lowercase hex chars`);
        if (!(e.bytes > 0) || !(e.width > 0) || !(e.height > 0)) problems.push(`${id}: bytes/width/height must be positive`);
        if (IGNORE_SCREENSHOTS.has(e.name)) problems.push(`${id}: is in IGNORE_SCREENSHOTS and must not be listed`);
        if (seen.has(id)) problems.push(`${id}: duplicate entry`);
        seen.add(id);
        if (prev && compareEntries(prev, e) > 0) {
            problems.push(`${id}: not sorted (engine, then name)`);
        }
        prev = e;
    }

    // Resurrection guard: baselines must never come back as committed files.
    try {
        const tracked = execFileSync('git', ['ls-files', '--', BASELINE_ROOT], { cwd: root, encoding: 'utf8' }).trim();
        if (tracked) {
            problems.push(
                `git-tracked PNGs under ${BASELINE_ROOT}/ — baselines live in R2, do not commit them:\n  ` +
                    tracked.split('\n').slice(0, 5).join('\n  ')
            );
        }
    } catch {
        console.warn('[manifest] git unavailable — skipping the resurrection guard');
    }
    return problems;
}

async function main(): Promise<void> {
    const check = process.argv.includes('--check');
    const remote = process.argv.includes('--remote');
    const root = process.cwd();
    const outPath = path.join(root, MANIFEST_PATH);

    if (check) {
        const problems = checkManifest(root);
        if (problems.length) {
            console.error(`[manifest] INVALID:\n  - ${problems.join('\n  - ')}`);
            process.exitCode = 1;
            return;
        }
        const manifest = JSON.parse(fs.readFileSync(outPath, 'utf8')) as Manifest;
        console.log(`[manifest] ok — ${manifest.screenshots.length} screenshots across engines`);
        if (remote) {
            const store = storeFromEnv();
            if (!store) {
                console.error(`[manifest] --remote needs credentials: set ${missingEnv().join(', ')}`);
                process.exitCode = 2;
                return;
            }
            const { verifyBaselines } = await import('./r2-sync');
            const missing = await verifyBaselines(root, store);
            if (missing.length) {
                console.error(`[manifest] ${missing.length} hash(es) missing in R2:\n  ${missing.join('\n  ')}`);
                process.exitCode = 1;
            } else {
                console.log('[manifest] every hash present in R2');
            }
        }
        return;
    }

    // Regeneration path: requires the cache tree (an absent tree would silently
    // produce an empty manifest and disable removed-screenshot detection).
    if (listEngineKeys(path.join(root, BASELINE_ROOT)).length === 0) {
        console.error('[manifest] baseline cache is empty — run `npm run screenshots:fetch` first (or promote a run)');
        process.exitCode = 1;
        return;
    }
    const json = manifestJson(root);
    fs.writeFileSync(outPath, json);
    const count = (JSON.parse(json) as Manifest).screenshots.length;
    console.log(`[manifest] wrote ${MANIFEST_PATH} (${count} screenshots)`);
}

if (require.main === module) {
    main().catch((e) => {
        console.error(`[manifest] ${(e as Error).message}`);
        process.exitCode = 1;
    });
}
